apiVersion: v1
kind: Service
metadata:
  name: panopta-agent-proxy
  labels:
    name: panopta-agent-proxy
  namespace: panopta
spec:
  ports:
  - port: 8443
    targetPort: 8443
    name: agent-proxy
  - port: 8090
    targetPort: 8090
    name: k8sengine
  selector:
    app: panopta-onsight
