apiVersion: v1
kind: Service
metadata:
  name: fortimonitor-agent-proxy
  labels:
    name: fortimonitor-agent-proxy
  namespace: fortimonitor
spec:
  ports:
  - port: 8443
    targetPort: 8443
    name: agent-proxy
  - port: 8090
    targetPort: 8090
    name: k8sengine
  selector:
    app: fortimonitor-onsight
