apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: panopta-onsight-pv-claim
  labels:
    app: panopta-onsight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: panopta-onsight
  labels:
    app: panopta-osight
    app.kubernetes.io/name: panopta
spec:
  selector:
     matchLabels:
        app: panopta-onsight
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: panopta-onsight
        version: 0.1.6
    spec:
      containers:
      - image: "panopta/onsight-vcollector:kubernetes"
        imagePullPolicy: Always
        name: panopta-onsight
        volumeMounts:
        - name: panopta-onsight-pv
          mountPath: /persistent/
        envFrom:
        - configMapRef:
            name: panopta-configmap
      volumes:
      - name: panopta-onsight-pv
        persistentVolumeClaim:
          claimName: panopta-onsight-pv-claim
      serviceAccountName: panopta-serviceaccount
