apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: panopta-onsight-pv-claim
  labels:
    app: panopta-onsight
  namespace: panopta
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: panopta-onsight
  labels:
    app: panopta-onsight
    app.kubernetes.io/name: panopta
  namespace: panopta
spec:
  selector:
     matchLabels:
        app: panopta-onsight
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: panopta-onsight
        version: 0.1.6
    spec:
      containers:
      - image: "panopta/onsight-vcollector:kubernetes"
        imagePullPolicy: Always
        name: panopta-onsight
        volumeMounts:
        - name: panopta-onsight-pv
          mountPath: /persistent/
        envFrom:
        - configMapRef:
            name: panopta-configmap
        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - 'n=$(date +"%s") && t=$(mysql ApplianceDB -e "SELECT value FROM ApplianceConfiguration WHERE name = \"last_sync_time\"" -sN | date "+%s" -f -) && d=$((n-t)) && echo "$d" && [ "$d" -le "600" ]'
          initialDelaySeconds: 600
          failureThreshold: 2
          periodSeconds: 30
      volumes:
      - name: panopta-onsight-pv
        persistentVolumeClaim:
          claimName: panopta-onsight-pv-claim
      serviceAccountName: panopta-serviceaccount
