apiVersion: v1
kind: ServiceAccount
metadata:
  name: panopta-serviceaccount
  namespace: panopta
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: panopta-role
  namespace: panopta
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes", "events", "componentstatuses", "persistentvolumes", "persistentvolumeclaims", "namespaces", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["metrics"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes/metrics"]
  verbs: ["get"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: panopta-rolebinding
  namespace: panopta
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: panopta-role
subjects:
- kind: ServiceAccount
  name: panopta-serviceaccount
  namespace: panopta
