apiVersion: v2
description: Helm chart for deploying FortiMonitor's Kubernetes monitoring infrastructure
name: fortimonitor
version: 1.2.2
dependencies:
  - name: kube-state-metrics
    version: 3.5.*
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.install
