apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-agent-proxy
  labels:
    name: {{ .Chart.Name }}-agent-proxy
spec:
  ports:
  - port: 8443
    targetPort: 8443
  selector:
    app: {{ .Chart.Name }}-onsight
