apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  CUSTOMER_KEY: {{ quote .Values.customer_key }}
  AGGREGATOR_URL: {{ quote .Values.aggregator_url }}
  AGENT_KEYS: ""
  AGENT_CONFIG: {{ quote .Values.agent_config | replace "\\n" "\\\\n" }}
  KUBE_STATE_ENDPOINT: {{ quote .Values.kubeStateMetrics.endpoint }}
