apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-onsight-pv-claim
  labels:
    app: {{ .Chart.Name }}-onsight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-onsight
  labels:
    app: {{ .Chart.Name }}-osight
    app.kubernetes.io/name: {{ include "panopta.name" . }}
    helm.sh/chart: {{ include "panopta.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
     matchLabels:
        app: {{ .Chart.Name }}-onsight
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-onsight
        version: {{ .Chart.Version }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - image: "{{ .Values.onsightImage.repository }}:{{ .Values.onsightImage.tag }}"
        imagePullPolicy: {{ .Values.onsightImage.pullPolicy }}
        name: {{ .Chart.Name }}-onsight
        volumeMounts:
        - name: {{ .Chart.Name }}-onsight-pv
          mountPath: /persistent/
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-configmap
        resources:
          requests:
            cpu: "{{ .Values.onsightRequests.cpu }}"
            memory: "{{ .Values.onsightRequests.memory }}"
            ephemeral-storage: "{{ .Values.onsightRequests.ephemeral }}"
          limits:
            ephemeral-storage: "{{ .Values.onsightRequests.ephemeral }}"
        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - 'n=$(date +"%s") && t=$(mysql ApplianceDB -e "SELECT value FROM ApplianceConfiguration WHERE name = \"last_sync_time\"" -sN | date "+%s" -f -) && d=$((n-t)) && echo "$d" && [ "$d" -le "600" ]'
          initialDelaySeconds: 600
          failureThreshold: 2
          periodSeconds: 30
      volumes:
      - name: {{ .Chart.Name }}-onsight-pv
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-onsight-pv-claim
      serviceAccountName: {{ .Chart.Name }}-serviceaccount
