apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  CUSTOMER_KEY: {{ quote .Values.customer_key }}
  CLUSTER_NAME: {{ quote .Values.clusterName }}
  AGGREGATOR_URL: {{ quote .Values.aggregator_url }}
  AGENT_CONFIG: {{ quote .Values.agent_config | replace "\\n" "\\\\n" }}
  TOP_N_NAMESPACES: {{ quote .Values.topNNamespaces }}
  PANOPTA_NAMESPACE: {{ quote .Release.Namespace }}
  KUBE_STATE_ENDPOINT: "http://{{ .Release.Name }}-kube-state-metrics.{{ .Release.Namespace }}.svc:8080"
