apiVersion: v1
description: A Helm chart for deploying Panopta's Kubernetes monitoring infrastructure
name: panopta
version: 0.3.0
dependencies:
  - name: kube-state-metrics
    version: 3.5.*
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.install
  - name: metrics-server
    version: 5.9.*
    repository: https://charts.bitnami.com/bitnami
    condition: metricsServer.install
