# Default values for panopta.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Size of your cluster. Possible values: small, medium, large
# See README for more information
size: medium

# Your Panopta customer key
customer_key: your-customer-key-123

# Name of the cluster as it will show in the controlpanel
clusterName: "Kubernetes Cluster"

agent_config: ""
# Replace the above line with a block like below
# to specifiy additional configuration options
# to be deployed on each node's panopta agent

# agent_config: |
#   [docker_image_mapping]
#   nginx=nginx
#   
#   [nginx]
#   foo=bar

aggregator_url: aggregator2.panopta.com

kubeStateMetrics:
  install: true

metricsServer:
  install: true

topNNamespaces: 0

onsightRequests:
  cpu: ""
  memory: ""
  ephemeral: ""

onsightImage:
  repository: panopta/onsight-vcollector
  tag: kubernetes
  pullPolicy: Always

agentImage:
  repository: panopta/agent
  tag: kubernetes
  pullPolicy: Always

kube-state-metrics:
  fullnameOverride: panopta-kube-state-metrics
  extraArgs:
    - "--enable-gzip-encoding"
  metricAllowlist:
    - kube_pod_container_resource_requests
    - kube_node_status_allocatable
    - kube_pod_info
    - kube_pod_container_status_restarts
    - kube_pod_container_status_restarts_total
    - kube_pod_container_status_waiting_reason
    - kube_pod_container_status_terminated_reason
    - kube_pod_container_status_last_terminated_reason
    - kube_node_spec_unschedulable
    - kube_node_status_condition

metrics-server:
  apiService:
    create: true
    # extraArgs: ['--kubelet-preferred-address-types', 'InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP']
