# Default values for panopta.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Your Panopta customer key
customer_key: your-customer-key-123

# Name of the cluster as it will show in the controlpanel
clusterName: "Kubernetes Cluster"

agent_config: ""
# Replace the above line with a block like below
# to specifiy additional configuration options
# to be deployed on each node's panopta agent

# agent_config: |
#   [docker_image_mapping]
#   nginx=nginx
#   
#   [nginx]
#   foo=bar

aggregator_url: aggregator2.panopta.com

kubeStateMetrics:
  install: true
  endpoint: http://kube-state-metrics.default.svc:8080

metricsServer:
  install: true

topNNamespaces: 25

onsightImage:
  repository: panopta/onsight-vcollector
  tag: kubernetes
  pullPolicy: Always

agentImage:
  repository: panopta/agent
  tag: kubernetes
  pullPolicy: Always

kube-state-metrics:
  fullnameOverride: kube-state-metrics

metrics-server:
  args: ['--kubelet-preferred-address-types', 'InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP']
