apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: panopta-metrics-server-auth-delegator
  namespace: kube-system
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/instance: panopta
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: panopta-metrics-server
    namespace: panopta
