apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fortimonitor-metrics-server
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/instance: fortimonitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fortimonitor-metrics-server
subjects:
  - kind: ServiceAccount
    name: fortimonitor-metrics-server
    namespace: kube-system
