apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fortimonitor-metrics-server-auth-reader
  namespace: kube-system
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/instance: fortimonitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: fortimonitor-metrics-server
    namespace: fortimonitor
