apiVersion: v1
kind: ServiceAccount
metadata:
  name: panopta-metrics-server
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/instance: panopta
automountServiceAccountToken: true
